// GENERATED by scripts/upload_glb_catbox.ps1 — direct HTTPS links (catbox.moe).

const glbRemoteUrls = <String, String>{
  '2018_audi_rs3_sportback.glb': 'https://files.catbox.moe/wxqkvg.glb',
  '2019_porsche_panamera_turbo.glb': 'https://files.catbox.moe/k4zxik.glb',
  '2020_lexus_lc.glb': 'https://files.catbox.moe/1uiig2.glb',
  '2021_honda_accord.glb': 'https://files.catbox.moe/ewfo2x.glb',
  '2022_porsche_cayenne_turbo_gt.glb': 'https://files.catbox.moe/ae5p3l.glb',
  '2023_kia_sportage_gt_line.glb': 'https://files.catbox.moe/57sp46.glb',
  '2024_ford_f150_raptor_r.glb': 'https://files.catbox.moe/w7cz3f.glb',
  '2025_bmw_m5_sedan.glb': 'https://files.catbox.moe/nmlum6.glb',
  '2025_mercedes_g_class_amg_g63.glb': 'https://files.catbox.moe/hor8e7.glb',
  '2025_volkswagen_golf_r_black_edition.glb': 'https://files.catbox.moe/les6mz.glb',
  '2025_xiaomi_yu7.glb': 'https://files.catbox.moe/wu4d5m.glb',
  'infiniti_q60_project_black_s.glb': 'https://files.catbox.moe/qkrsck.glb',
  'jeep_wrangler_rubicon.glb': 'https://files.catbox.moe/fng15u.glb',
  'mazda_rx7.glb': 'https://files.catbox.moe/m61gug.glb',
  'mini_cooper_s_facelift.glb': 'https://files.catbox.moe/0y1fmu.glb',
  'mitsubishi_lancer_evolution_ix.glb': 'https://files.catbox.moe/78seaw.glb',
  'nissan_terra_2020.glb': 'https://files.catbox.moe/xxzme9.glb',
  'opel_astra_l.glb': 'https://files.catbox.moe/fktcgd.glb',
  'polestar_1.glb': 'https://files.catbox.moe/mja2u6.glb',
  'renault_twingo_gt.glb': 'https://files.catbox.moe/ktpihv.glb',
  'skoda_fabia_rs_wrc.glb': 'https://files.catbox.moe/a0oah3.glb',
  'tesla_model_3.glb': 'https://files.catbox.moe/u1xwif.glb',
  'toyota_gr_supra.glb': 'https://files.catbox.moe/rr4fs0.glb',
  'volvo_s90_recharge.glb': 'https://files.catbox.moe/u25e07.glb',
  'zeekr_7x_2025.glb': 'https://files.catbox.moe/7ik36f.glb',
};

String? glbRemoteUrlForFile(String fileName) => glbRemoteUrls[fileName];
