# Uploads all GLB models to catbox.moe (permanent anonymous hosting)
# and generates lib/data/glb_remote_urls.dart with direct HTTPS links.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$modelsDir = Join-Path $root "hosting\public\assets\assets\models"
$outDart = Join-Path $root "lib\data\glb_remote_urls.dart"
$map = @{}

Get-ChildItem $modelsDir -Filter *.glb | Sort-Object Name | ForEach-Object {
  $file = $_.FullName
  $name = $_.Name
  Write-Host "Uploading $name ($([math]::Round($_.Length/1MB,1)) MB)..."
  $resp = curl.exe -s -F "reqtype=fileupload" -F "fileToUpload=@$file" "https://catbox.moe/user/api.php"
  if ($resp -notmatch '^https://') {
    throw "Upload failed for ${name}: $resp"
  }
  $map[$name] = $resp.Trim()
  Write-Host "  -> $($map[$name])"
}

$lines = @(
  '// GENERATED by scripts/upload_glb_catbox.ps1 — do not edit manually.',
  '',
  'const glbRemoteUrls = <String, String>{'
)
foreach ($kv in ($map.GetEnumerator() | Sort-Object Name)) {
  $lines += ('  ''{0}'': ''{1}'',' -f $kv.Key, $kv.Value)
}
$lines += '};'
$lines += ''
$lines += 'String? glbRemoteUrlForFile(String fileName) => glbRemoteUrls[fileName];'
$lines += ''

Set-Content -Path $outDart -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $($map.Count) URLs to $outDart"
